[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

xrandr --dpi 96
xset s off -dpms
customkeys
xdg-mime default mupdf.desktop application/pdf
xdg-mime default feh.desktop image/png
xdg-mime default feh.desktop image/jpg

feh --bg-fill ~/.wallpaper.png
unclutter &
picom &
dunst &
lxpolkit &
dwm_bar &
exec dwm
