# For full documentation of this config format, look man 5 alacritty

#import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.yaml"]

[window]
opacity = 0.9
[window.padding]
x = 3
y = 3

[font]
size = 10.0
[font.normal]
family = "Hack Nerd Font Mono"

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
